#!/usr/bin/env bash
# Regenerates the SQLite-schema test fixtures in this folder from the default (PostgreSQL-style)
# fixtures in ../. The data is the same, but the tables mirror the schema of the exported SQLite
# provenance database (provenance.sqlite): every column is TEXT, NULLs are stored as '' and
# booleans as 't'/'f'.
#
# Usage: ./generate.sh   (requires the sqlite3 CLI)
set -euo pipefail

cd "$(dirname "$0")"
SRC=..
TMP_DB=$(mktemp --suffix=.sqlite)
trap 'rm -f "$TMP_DB"' EXIT

for f in countries versions vendor_locations vendors github_contributors mines licenses all_urls; do
  sqlite3 "$TMP_DB" < "$SRC/$f.sql"
done

# Column mapping: <table>|<d4 columns>|<select expression list over the source table>
TABLES=(
  "countries|id, country_name|id, country_name"
  "mines|id, purl_type, mine_name|id, purl_type, name"
  "versions|id, version_name, semver|id, version_name, semver"
  "licenses|id, license_name, spdx_id, is_spdx|id, license_name, spdx_id, CASE WHEN is_spdx THEN 't' ELSE 'f' END"
  "vendors|id, username, type, mine_id|id, username, type, mine_id"
  "github_contributors|purl_name, contributor|purl_name, contributor"
  "vendor_locations|vendor_id, declared_location, curated_countries_ids, timezone_based_country|vendor_id, declared_location, curated_countries_ids, timezone_based_country"
  "too_many_contributors|purl_name, mine_id|purl_name, mine_id"
  "all_urls|package_hash, component, purl_name, mine_id, vendor, version, version_id, date, license_id, is_mined|package_hash, component, purl_name, mine_id, vendor, version, version_id, date, license_id, CASE WHEN is_mined IS NULL THEN '' WHEN is_mined THEN 't' ELSE 'f' END"
)

# Indexes present in provenance.sqlite
declare -A INDEXES=(
  [countries]="CREATE INDEX idx_countries_id ON countries (id);"
  [mines]="CREATE INDEX idx_mines_purl_type ON mines (purl_type, id);"
  [versions]="CREATE INDEX idx_versions_version_name_id_semver ON versions (version_name, id, semver);
CREATE INDEX idx_versions_id_version_name_semver ON versions (id, version_name, semver);"
  [licenses]="CREATE INDEX idx_license_id_license_name_spdx_id_is_spdx ON licenses (id, license_name, spdx_id, is_spdx);"
  [vendors]="CREATE INDEX idx_vendors_id ON vendors (id);
CREATE INDEX idx_vendors_username_type_mine_id ON vendors (username, type, mine_id);"
  [github_contributors]="CREATE INDEX idx_github_contributors_purl_name ON github_contributors (purl_name);
CREATE INDEX idx_github_contributors_contributor ON github_contributors (contributor);"
  [vendor_locations]="CREATE INDEX idx_vendor_locations_vendor_id ON vendor_locations (vendor_id);
CREATE INDEX idx_vendor_locations_declared_location ON vendor_locations (declared_location);"
  [too_many_contributors]="CREATE INDEX idx_too_many_contributors_purl_name_mine_id ON too_many_contributors (purl_name, mine_id);"
  [all_urls]="CREATE INDEX idx_allurls_name ON all_urls (purl_name, mine_id, license_id, version_id);
CREATE INDEX idx_allurls_comp ON all_urls (component, vendor, mine_id);
CREATE INDEX idx_allurls_phash ON all_urls (purl_name, package_hash, mine_id, version_id);"
)

for entry in "${TABLES[@]}"; do
  IFS='|' read -r table cols exprs <<< "$entry"
  # Wrap every source expression as COALESCE(CAST(x AS TEXT), '') so values are TEXT and never NULL
  select=$(echo "$exprs" | awk -v RS=', ' '{gsub(/\n$/, ""); printf "%sCOALESCE(CAST(%s AS TEXT), %s)", (NR>1?", ":""), $0, "\x27\x27"}')
  coldefs=$(echo "$cols" | sed -E 's/([a-z_]+)/\1 TEXT/g')
  out="$table.sql"
  {
    echo "-- Generated by generate.sh from ../$([ "$table" = too_many_contributors ] && echo github_contributors || echo "$table").sql - do not edit by hand."
    echo "DROP TABLE IF EXISTS $table;"
    echo "CREATE TABLE $table ($coldefs);"
    sqlite3 -cmd ".mode insert $table" "$TMP_DB" "SELECT $select FROM $table;" |
      sed -E "s/^INSERT INTO $table VALUES/INSERT INTO $table ($cols) VALUES/"
    echo "${INDEXES[$table]}"
  } > "$out"
  echo "Wrote $out ($(grep -c '^INSERT' "$out") rows)"
done

echo "DROP TABLE IF EXISTS db_version;
CREATE TABLE db_version (package_name TEXT NOT NULL, schema_version TEXT NOT NULL, created_at TEXT NOT NULL, db_release TEXT NOT NULL);
INSERT INTO db_version VALUES ('provenance', '1.0.0', '2026-09-22T19:00Z', '26.09');" > db_version.sql
echo "Wrote db_version.sql"
