-- Generated by generate.sh from ../licenses.sql - do not edit by hand.
DROP TABLE IF EXISTS licenses;
CREATE TABLE licenses (id TEXT, license_name TEXT, spdx_id TEXT, is_spdx TEXT);
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('109','3-Clause BSD License','BSD-3-Clause','t');
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('552','Apache 2.0','Apache-2.0','t');
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('850','Apache License 2.0','Apache-2.0','t');
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('1378','BSD','0BSD','t');
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('4863','ISC','ISC','t');
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('5236','LGPLv2.1+','LGPL-2.1-or-later','t');
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('5614','MIT','MIT','t');
INSERT INTO licenses (id, license_name, spdx_id, is_spdx) VALUES('9999','','','f');
CREATE INDEX idx_license_id_license_name_spdx_id_is_spdx ON licenses (id, license_name, spdx_id, is_spdx);
