-- Generated by generate.sh from ../github_contributors.sql - do not edit by hand.
DROP TABLE IF EXISTS too_many_contributors;
CREATE TABLE too_many_contributors (purl_name TEXT, mine_id TEXT);
INSERT INTO too_many_contributors (purl_name, mine_id) VALUES('torvalds/linux','5');
CREATE INDEX idx_too_many_contributors_purl_name_mine_id ON too_many_contributors (purl_name, mine_id);
