-- Generated by generate.sh from ../vendors.sql - do not edit by hand.
DROP TABLE IF EXISTS vendors;
CREATE TABLE vendors (id TEXT, username TEXT, type TEXT, mine_id TEXT);
INSERT INTO vendors (id, username, type, mine_id) VALUES('1405399','scanoss-qg','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('1405465','mscasso-scanoss','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('1320559','lijie','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('2108508','sumitbsn','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('1485164','ChrisADR','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('1406024','perezale','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('1405464','scanossjs','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('3236055','jeronimoortiz','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('3277960','scanossjeronimo','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('1197052','ulm','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('351225','torvalds','User','5');
INSERT INTO vendors (id, username, type, mine_id) VALUES('1620783','TorstenScheck','User','5');
CREATE INDEX idx_vendors_id ON vendors (id);
CREATE INDEX idx_vendors_username_type_mine_id ON vendors (username, type, mine_id);
