name: Release
# Build and attach supported artifacts a draft release tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get tags to allow build script to get build version

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x


      - name: Build Unpublished papi
        run: |
          sudo apt update && sudo apt install -y protobuf-compiler
          git clone -b SCP118-AddProvenanze https://github.com/scanoss/papi ../papi
          cd ../papi
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
          go get github.com/grpc-ecosystem/grpc-gateway/v2/internal/descriptor@v2.18.0
          go install \
                  github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
                  github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
                  google.golang.org/protobuf/cmd/protoc-gen-go \
                  google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go install github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
          make build_go

      - name: Build
        run: |
          make build_amd
          make build_arm

#      - name: Unit Test
#        run: make unit_test

      - name: Package
        run: |
          make package_amd
          make package_arm

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            target/scanoss-provenance-api-linux-amd64
            target/scanoss-provenance-api-linux-arm64
            scanoss-provenance-api_linux-amd64_${{ github.ref_name }}-1.tgz
            scanoss-provenance-api_linux-arm64_${{ github.ref_name }}-1.tgz